
  blackfire:
    image: blackfire/blackfire
    ports: ["8707"]
    environment:
      # Exposes BLACKFIRE_SERVER_* environment variables from the host
      - BLACKFIRE_CLIENT_ID
      - BLACKFIRE_CLIENT_TOKEN
      - BLACKFIRE_SERVER_ID
      - BLACKFIRE_SERVER_TOKEN