
  phpmyadmin:
    build:
      context: config/phpmyadmin
      args:
        PHP_MEMORY_LIMIT: ${PHP_MEMORY_LIMIT}
        PHP_UPLOAD_MAX_FILESIZE: ${PHP_UPLOAD_MAX_FILESIZE}
        DEFAULT_TIMEZONE: ${DEFAULT_TIMEZONE}
        PHP_MAX_EXECUTION_TIME: ${PHP_MAX_EXECUTION_TIME}

    environment:
      - PMA_HOST=mysql
      - TZ=${DEFAULT_TIMEZONE}
    ports:
      - ${PORT_PMA}:80
    volumes:
      - ./config/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
